spring:
  application:
    name: spring_review
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: false # ???? ???? ???? ??? ???
  jpa:
    hibernate:
      ddl-auto: update # DDL ?? ?? ??
    properties:
      hibernate:
        default_batch_fetch_size: 100 # LAZY ??? ?, ??? ??? ??
        format_sql: true # SQL ???
        highlight_sql: true # SQL ?????
        use_sql_comments: true # SQL ?? ??
logging:
  level:
    com.back: DEBUG
    org.hibernate.SQL: DEBUG # SQL ?? ??
    org.hibernate.orm.jdbc.bind: TRACE # SQL ??? ??
    org.hibernate.orm.jdbc.extract: TRACE # SQL ?? ??
    org.springframework.transaction.interceptor: TRACE # ???? ??